name: API Proxy
on:
  repository_dispatch:
    types: [proxy-request]
  workflow_dispatch:
    inputs:
      apiKey:
        description: 'API Key'
        required: true
      messages:
        description: 'Messages'
        required: true

permissions: write-all

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install axios

      - name: Process Request
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            console.log('Processing request...');
            try {
              const apiKey = context.payload.client_payload?.apiKey || context.inputs.apiKey;
              const messages = context.payload.client_payload?.messages || JSON.parse(context.inputs.messages);
              
              const response = await axios({
                method: 'POST',
                url: 'https://api.kksjj.org/v1/chat/completions',
                headers: {
                  'Authorization': `Bearer ${apiKey}`,
                  'Content-Type': 'application/json'
                },
                data: {
                  model: 'gpt-3.5-turbo',
                  messages: messages,
                  temperature: 0.7,
                  max_tokens: 2000
                },
                timeout: 30000
              });
              
              console.log('Request successful');
              return {
                status: 'success',
                data: response.data
              };
              
            } catch (error) {
              console.error('Error:', error);
              return {
                status: 'error',
                message: error.message
              };
            }
