name: API Proxy
on:
  repository_dispatch:   # 使用 repository_dispatch 事件
    types: [proxy-request]

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Process Request
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            try {
              console.log('Processing request...');
              const { apiKey, messages } = context.payload.client_payload;
              
              // 发送请求到实际的 API
              const response = await axios({
                method: 'POST',
                url: 'https://api.kksjj.org/v1/chat/completions',
                headers: {
                  'Authorization': `Bearer ${apiKey}`,
                  'Content-Type': 'application/json'
                },
                data: {
                  model: 'gpt-3.5-turbo',
                  messages: messages
                },
                timeout: 30000
              });
              
              console.log('Request successful');
              return response.data;
              
            } catch (error) {
              console.error('Error:', error);
              throw error;
            }
