name: API Proxy
on:
  repository_dispatch:
    types: [proxy-request]
  workflow_dispatch:  # 添加手动触发选项，方便测试

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Process Request
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Processing request...');
            const axios = require('axios');
            try {
              const { apiKey, messages } = context.payload.client_payload;
              
              const response = await axios({
                method: 'POST',
                url: 'https://api.kksjj.org/v1/chat/completions',
                headers: {
                  'Authorization': `Bearer ${apiKey}`,
                  'Content-Type': 'application/json'
                },
                data: {
                  model: 'gpt-3.5-turbo',
                  messages: messages,
                  temperature: 0.7,
                  max_tokens: 2000
                },
                timeout: 30000
              });
              
              console.log('Request successful');
              return {
                status: 'success',
                data: response.data
              };
              
            } catch (error) {
              console.error('Error:', error);
              return {
                status: 'error',
                message: error.message
              };
            }
